# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap(
    {
        "retry_policy": "retryPolicy",
        "retry_period": "retryPeriod",
        "retry_max_count": "retryMaxCount",
    }
)
class ClientRetrySettings(BaseModel):
    """ClientRetrySettings

    :param retry_policy: retry_policy, defaults to None
    :type retry_policy: str, optional
    :param retry_period: retry_period, defaults to None
    :type retry_period: int, optional
    :param retry_max_count: retry_max_count, defaults to None
    :type retry_max_count: int, optional
    """

    def __init__(
        self,
        retry_policy: str = None,
        retry_period: int = None,
        retry_max_count: int = None,
        **kwargs
    ):
        """ClientRetrySettings

        :param retry_policy: retry_policy, defaults to None
        :type retry_policy: str, optional
        :param retry_period: retry_period, defaults to None
        :type retry_period: int, optional
        :param retry_max_count: retry_max_count, defaults to None
        :type retry_max_count: int, optional
        """
        if retry_policy is not None:
            self.retry_policy = self._define_str(
                "retry_policy", retry_policy, nullable=True
            )
        if retry_period is not None:
            self.retry_period = self._define_number(
                "retry_period", retry_period, nullable=True
            )
        if retry_max_count is not None:
            self.retry_max_count = self._define_number(
                "retry_max_count", retry_max_count, nullable=True
            )
        self._kwargs = kwargs
