# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap(
    {
        "listing_create_callback_url": "listingCreateCallbackUrl",
        "listing_update_callback_url": "listingUpdateCallbackUrl",
        "listing_delete_callback_url": "listingDeleteCallbackUrl",
    }
)
class ClientCallbacks(BaseModel):
    """ClientCallbacks

    :param listing_create_callback_url: listing_create_callback_url, defaults to None
    :type listing_create_callback_url: str, optional
    :param listing_update_callback_url: listing_update_callback_url, defaults to None
    :type listing_update_callback_url: str, optional
    :param listing_delete_callback_url: listing_delete_callback_url, defaults to None
    :type listing_delete_callback_url: str, optional
    """

    def __init__(
        self,
        listing_create_callback_url: str = None,
        listing_update_callback_url: str = None,
        listing_delete_callback_url: str = None,
        **kwargs
    ):
        """ClientCallbacks

        :param listing_create_callback_url: listing_create_callback_url, defaults to None
        :type listing_create_callback_url: str, optional
        :param listing_update_callback_url: listing_update_callback_url, defaults to None
        :type listing_update_callback_url: str, optional
        :param listing_delete_callback_url: listing_delete_callback_url, defaults to None
        :type listing_delete_callback_url: str, optional
        """
        if listing_create_callback_url is not None:
            self.listing_create_callback_url = self._define_str(
                "listing_create_callback_url",
                listing_create_callback_url,
                nullable=True,
            )
        if listing_update_callback_url is not None:
            self.listing_update_callback_url = self._define_str(
                "listing_update_callback_url",
                listing_update_callback_url,
                nullable=True,
            )
        if listing_delete_callback_url is not None:
            self.listing_delete_callback_url = self._define_str(
                "listing_delete_callback_url",
                listing_delete_callback_url,
                nullable=True,
            )
        self._kwargs = kwargs
