# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"zip_code": "zipCode", "time_zone_key": "timeZoneKey"})
class EditAddressPrincipal(BaseModel):
    """EditAddressPrincipal

    :param address1: address1, defaults to None
    :type address1: str, optional
    :param address2: address2, defaults to None
    :type address2: str, optional
    :param city: city, defaults to None
    :type city: str, optional
    :param state: state, defaults to None
    :type state: str, optional
    :param zip_code: zip_code, defaults to None
    :type zip_code: str, optional
    :param country: country, defaults to None
    :type country: str, optional
    :param latitude: latitude, defaults to None
    :type latitude: float, optional
    :param longitude: longitude, defaults to None
    :type longitude: float, optional
    :param time_zone_key: time_zone_key, defaults to None
    :type time_zone_key: int, optional
    :param company: company, defaults to None
    :type company: str, optional
    """

    def __init__(
        self,
        address1: str = None,
        address2: str = None,
        city: str = None,
        state: str = None,
        zip_code: str = None,
        country: str = None,
        latitude: float = None,
        longitude: float = None,
        time_zone_key: int = None,
        company: str = None,
        **kwargs
    ):
        """EditAddressPrincipal

        :param address1: address1, defaults to None
        :type address1: str, optional
        :param address2: address2, defaults to None
        :type address2: str, optional
        :param city: city, defaults to None
        :type city: str, optional
        :param state: state, defaults to None
        :type state: str, optional
        :param zip_code: zip_code, defaults to None
        :type zip_code: str, optional
        :param country: country, defaults to None
        :type country: str, optional
        :param latitude: latitude, defaults to None
        :type latitude: float, optional
        :param longitude: longitude, defaults to None
        :type longitude: float, optional
        :param time_zone_key: time_zone_key, defaults to None
        :type time_zone_key: int, optional
        :param company: company, defaults to None
        :type company: str, optional
        """
        if address1 is not None:
            self.address1 = self._define_str("address1", address1, nullable=True)
        if address2 is not None:
            self.address2 = self._define_str("address2", address2, nullable=True)
        if city is not None:
            self.city = self._define_str("city", city, nullable=True)
        if state is not None:
            self.state = self._define_str("state", state, nullable=True)
        if zip_code is not None:
            self.zip_code = self._define_str("zip_code", zip_code, nullable=True)
        if country is not None:
            self.country = self._define_str("country", country, nullable=True)
        if latitude is not None:
            self.latitude = self._define_number("latitude", latitude, nullable=True)
        if longitude is not None:
            self.longitude = self._define_number("longitude", longitude, nullable=True)
        if time_zone_key is not None:
            self.time_zone_key = self._define_number(
                "time_zone_key", time_zone_key, nullable=True
            )
        if company is not None:
            self.company = self._define_str("company", company, nullable=True)
        self._kwargs = kwargs
