# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .user_fields import UserFields
from .user_data_fields import UserDataFields
from .logical_fields import LogicalFields


@JsonMap(
    {
        "construction_type": "constructionType",
        "owner_occupied": "ownerOccupied",
        "cross_streets": "crossStreets",
        "building_class": "buildingClass",
        "building_id": "buildingId",
        "last_trans_price": "lastTransPrice",
        "last_trans_date": "lastTransDate",
        "map_coord": "mapCoord",
        "web_site": "webSite",
        "user_fields": "userFields",
        "user_data_fields": "userDataFields",
        "logical_fields": "logicalFields",
    }
)
class EditPropertyDetails(BaseModel):
    """EditPropertyDetails

    :param assessed: assessed, defaults to None
    :type assessed: float, optional
    :param construction_type: construction_type, defaults to None
    :type construction_type: str, optional
    :param owner_occupied: owner_occupied, defaults to None
    :type owner_occupied: bool, optional
    :param cross_streets: cross_streets, defaults to None
    :type cross_streets: str, optional
    :param building_class: building_class, defaults to None
    :type building_class: str, optional
    :param location: location, defaults to None
    :type location: str, optional
    :param description: description, defaults to None
    :type description: str, optional
    :param building_id: building_id, defaults to None
    :type building_id: str, optional
    :param last_trans_price: last_trans_price, defaults to None
    :type last_trans_price: float, optional
    :param last_trans_date: last_trans_date, defaults to None
    :type last_trans_date: str, optional
    :param map_coord: map_coord, defaults to None
    :type map_coord: str, optional
    :param acres: acres, defaults to None
    :type acres: float, optional
    :param units: units, defaults to None
    :type units: int, optional
    :param sqft: sqft, defaults to None
    :type sqft: float, optional
    :param parcel: parcel, defaults to None
    :type parcel: str, optional
    :param stories: stories, defaults to None
    :type stories: int, optional
    :param market: market, defaults to None
    :type market: str, optional
    :param submarket: submarket, defaults to None
    :type submarket: str, optional
    :param zoning: zoning, defaults to None
    :type zoning: str, optional
    :param web_site: web_site, defaults to None
    :type web_site: str, optional
    :param user_fields: user_fields, defaults to None
    :type user_fields: UserFields, optional
    :param user_data_fields: user_data_fields, defaults to None
    :type user_data_fields: UserDataFields, optional
    :param logical_fields: logical_fields, defaults to None
    :type logical_fields: LogicalFields, optional
    """

    def __init__(
        self,
        assessed: float = None,
        construction_type: str = None,
        owner_occupied: bool = None,
        cross_streets: str = None,
        building_class: str = None,
        location: str = None,
        description: str = None,
        building_id: str = None,
        last_trans_price: float = None,
        last_trans_date: str = None,
        map_coord: str = None,
        acres: float = None,
        units: int = None,
        sqft: float = None,
        parcel: str = None,
        stories: int = None,
        market: str = None,
        submarket: str = None,
        zoning: str = None,
        web_site: str = None,
        user_fields: UserFields = None,
        user_data_fields: UserDataFields = None,
        logical_fields: LogicalFields = None,
        **kwargs,
    ):
        """EditPropertyDetails

        :param assessed: assessed, defaults to None
        :type assessed: float, optional
        :param construction_type: construction_type, defaults to None
        :type construction_type: str, optional
        :param owner_occupied: owner_occupied, defaults to None
        :type owner_occupied: bool, optional
        :param cross_streets: cross_streets, defaults to None
        :type cross_streets: str, optional
        :param building_class: building_class, defaults to None
        :type building_class: str, optional
        :param location: location, defaults to None
        :type location: str, optional
        :param description: description, defaults to None
        :type description: str, optional
        :param building_id: building_id, defaults to None
        :type building_id: str, optional
        :param last_trans_price: last_trans_price, defaults to None
        :type last_trans_price: float, optional
        :param last_trans_date: last_trans_date, defaults to None
        :type last_trans_date: str, optional
        :param map_coord: map_coord, defaults to None
        :type map_coord: str, optional
        :param acres: acres, defaults to None
        :type acres: float, optional
        :param units: units, defaults to None
        :type units: int, optional
        :param sqft: sqft, defaults to None
        :type sqft: float, optional
        :param parcel: parcel, defaults to None
        :type parcel: str, optional
        :param stories: stories, defaults to None
        :type stories: int, optional
        :param market: market, defaults to None
        :type market: str, optional
        :param submarket: submarket, defaults to None
        :type submarket: str, optional
        :param zoning: zoning, defaults to None
        :type zoning: str, optional
        :param web_site: web_site, defaults to None
        :type web_site: str, optional
        :param user_fields: user_fields, defaults to None
        :type user_fields: UserFields, optional
        :param user_data_fields: user_data_fields, defaults to None
        :type user_data_fields: UserDataFields, optional
        :param logical_fields: logical_fields, defaults to None
        :type logical_fields: LogicalFields, optional
        """
        if assessed is not None:
            self.assessed = self._define_number("assessed", assessed, nullable=True)
        if construction_type is not None:
            self.construction_type = self._define_str(
                "construction_type", construction_type, nullable=True
            )
        if owner_occupied is not None:
            self.owner_occupied = owner_occupied
        if cross_streets is not None:
            self.cross_streets = self._define_str(
                "cross_streets", cross_streets, nullable=True
            )
        if building_class is not None:
            self.building_class = self._define_str(
                "building_class", building_class, nullable=True
            )
        if location is not None:
            self.location = self._define_str("location", location, nullable=True)
        if description is not None:
            self.description = self._define_str(
                "description", description, nullable=True
            )
        if building_id is not None:
            self.building_id = self._define_str(
                "building_id", building_id, nullable=True
            )
        if last_trans_price is not None:
            self.last_trans_price = self._define_number(
                "last_trans_price", last_trans_price, nullable=True
            )
        if last_trans_date is not None:
            self.last_trans_date = self._define_str(
                "last_trans_date", last_trans_date, nullable=True
            )
        if map_coord is not None:
            self.map_coord = self._define_str("map_coord", map_coord, nullable=True)
        if acres is not None:
            self.acres = self._define_number("acres", acres, nullable=True)
        if units is not None:
            self.units = self._define_number("units", units, nullable=True)
        if sqft is not None:
            self.sqft = self._define_number("sqft", sqft, nullable=True)
        if parcel is not None:
            self.parcel = self._define_str("parcel", parcel, nullable=True)
        if stories is not None:
            self.stories = self._define_number("stories", stories, nullable=True)
        if market is not None:
            self.market = self._define_str("market", market, nullable=True)
        if submarket is not None:
            self.submarket = self._define_str("submarket", submarket, nullable=True)
        if zoning is not None:
            self.zoning = self._define_str("zoning", zoning, nullable=True)
        if web_site is not None:
            self.web_site = self._define_str("web_site", web_site, nullable=True)
        if user_fields is not None:
            self.user_fields = self._define_object(user_fields, UserFields)
        if user_data_fields is not None:
            self.user_data_fields = self._define_object(
                user_data_fields, UserDataFields
            )
        if logical_fields is not None:
            self.logical_fields = self._define_object(logical_fields, LogicalFields)
        self._kwargs = kwargs
