# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class EditNotes(BaseModel):
    """EditNotes

    :param notes: notes, defaults to None
    :type notes: str, optional
    """

    def __init__(self, notes: str = None, **kwargs):
        """EditNotes

        :param notes: notes, defaults to None
        :type notes: str, optional
        """
        if notes is not None:
            self.notes = self._define_str("notes", notes, nullable=True)
        self._kwargs = kwargs
