# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"user_name": "userName"})
class EventParticipant(BaseModel):
    """EventParticipant

    :param key: key, defaults to None
    :type key: str, optional
    :param user_name: user_name, defaults to None
    :type user_name: str, optional
    :param email: email, defaults to None
    :type email: str, optional
    """

    def __init__(
        self, key: str = None, user_name: str = None, email: str = None, **kwargs
    ):
        """EventParticipant

        :param key: key, defaults to None
        :type key: str, optional
        :param user_name: user_name, defaults to None
        :type user_name: str, optional
        :param email: email, defaults to None
        :type email: str, optional
        """
        if key is not None:
            self.key = self._define_str("key", key, nullable=True)
        if user_name is not None:
            self.user_name = self._define_str("user_name", user_name, nullable=True)
        if email is not None:
            self.email = self._define_str("email", email, nullable=True)
        self._kwargs = kwargs
