# This file was generated by liblab | https://liblab.com/

from enum import Enum


class HistorySorting(Enum):
    """An enumeration representing different categories.

    :cvar DEFAULT: "Default"
    :vartype DEFAULT: str
    :cvar EVENTTYPE: "EventType"
    :vartype EVENTTYPE: str
    :cvar EVENTTYPEDESC: "EventTypeDesc"
    :vartype EVENTTYPEDESC: str
    :cvar STATUS: "Status"
    :vartype STATUS: str
    :cvar STATUSDESC: "StatusDesc"
    :vartype STATUSDESC: str
    :cvar STARTDATE: "StartDate"
    :vartype STARTDATE: str
    :cvar STARTDATEDESC: "StartDateDesc"
    :vartype STARTDATEDESC: str
    :cvar ENDDATE: "EndDate"
    :vartype ENDDATE: str
    :cvar ENDDATEDESC: "EndDateDesc"
    :vartype ENDDATEDESC: str
    :cvar SUBJECT: "Subject"
    :vartype SUBJECT: str
    :cvar SUBJECTDESC: "SubjectDesc"
    :vartype SUBJECTDESC: str
    :cvar PROJECT: "Project"
    :vartype PROJECT: str
    :cvar PROJECTDESC: "ProjectDesc"
    :vartype PROJECTDESC: str
    :cvar NOTES: "Notes"
    :vartype NOTES: str
    :cvar NOTESDESC: "NotesDesc"
    :vartype NOTESDESC: str
    :cvar OWNER: "Owner"
    :vartype OWNER: str
    :cvar OWNERDESC: "OwnerDesc"
    :vartype OWNERDESC: str
    :cvar TEAM: "Team"
    :vartype TEAM: str
    :cvar TEAMDESC: "TeamDesc"
    :vartype TEAMDESC: str
    :cvar USER1: "User1"
    :vartype USER1: str
    :cvar USER1DESC: "User1Desc"
    :vartype USER1DESC: str
    :cvar USER2: "User2"
    :vartype USER2: str
    :cvar USER2DESC: "User2Desc"
    :vartype USER2DESC: str
    :cvar USER3: "User3"
    :vartype USER3: str
    :cvar USER3DESC: "User3Desc"
    :vartype USER3DESC: str
    :cvar USER4: "User4"
    :vartype USER4: str
    :cvar USER4DESC: "User4Desc"
    :vartype USER4DESC: str
    :cvar LOGICAL1: "Logical1"
    :vartype LOGICAL1: str
    :cvar LOGICAL1DESC: "Logical1Desc"
    :vartype LOGICAL1DESC: str
    :cvar LOGICAL2: "Logical2"
    :vartype LOGICAL2: str
    :cvar LOGICAL2DESC: "Logical2Desc"
    :vartype LOGICAL2DESC: str
    :cvar LOGICAL3: "Logical3"
    :vartype LOGICAL3: str
    :cvar LOGICAL3DESC: "Logical3Desc"
    :vartype LOGICAL3DESC: str
    :cvar LOGICAL4: "Logical4"
    :vartype LOGICAL4: str
    :cvar LOGICAL4DESC: "Logical4Desc"
    :vartype LOGICAL4DESC: str
    """

    DEFAULT = "Default"
    EVENTTYPE = "EventType"
    EVENTTYPEDESC = "EventTypeDesc"
    STATUS = "Status"
    STATUSDESC = "StatusDesc"
    STARTDATE = "StartDate"
    STARTDATEDESC = "StartDateDesc"
    ENDDATE = "EndDate"
    ENDDATEDESC = "EndDateDesc"
    SUBJECT = "Subject"
    SUBJECTDESC = "SubjectDesc"
    PROJECT = "Project"
    PROJECTDESC = "ProjectDesc"
    NOTES = "Notes"
    NOTESDESC = "NotesDesc"
    OWNER = "Owner"
    OWNERDESC = "OwnerDesc"
    TEAM = "Team"
    TEAMDESC = "TeamDesc"
    USER1 = "User1"
    USER1DESC = "User1Desc"
    USER2 = "User2"
    USER2DESC = "User2Desc"
    USER3 = "User3"
    USER3DESC = "User3Desc"
    USER4 = "User4"
    USER4DESC = "User4Desc"
    LOGICAL1 = "Logical1"
    LOGICAL1DESC = "Logical1Desc"
    LOGICAL2 = "Logical2"
    LOGICAL2DESC = "Logical2Desc"
    LOGICAL3 = "Logical3"
    LOGICAL3DESC = "Logical3Desc"
    LOGICAL4 = "Logical4"
    LOGICAL4DESC = "Logical4Desc"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, HistorySorting._member_map_.values()))
