# This file was generated by liblab | https://liblab.com/

from enum import Enum


class LeadObjectType(Enum):
    """An enumeration representing different categories.

    :cvar NONE: "None"
    :vartype NONE: str
    :cvar CONTACT: "Contact"
    :vartype CONTACT: str
    :cvar PROPERTY: "Property"
    :vartype PROPERTY: str
    :cvar COMPANY: "Company"
    :vartype COMPANY: str
    :cvar SPACE: "Space"
    :vartype SPACE: str
    """

    NONE = "None"
    CONTACT = "Contact"
    PROPERTY = "Property"
    COMPANY = "Company"
    SPACE = "Space"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, LeadObjectType._member_map_.values()))
