# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class LogicalFields(BaseModel):
    """LogicalFields

    :param logical1: logical1, defaults to None
    :type logical1: bool, optional
    :param logical2: logical2, defaults to None
    :type logical2: bool, optional
    :param logical3: logical3, defaults to None
    :type logical3: bool, optional
    :param logical4: logical4, defaults to None
    :type logical4: bool, optional
    :param logical5: logical5, defaults to None
    :type logical5: bool, optional
    :param logical6: logical6, defaults to None
    :type logical6: bool, optional
    :param logical7: logical7, defaults to None
    :type logical7: bool, optional
    :param logical8: logical8, defaults to None
    :type logical8: bool, optional
    :param logical9: logical9, defaults to None
    :type logical9: bool, optional
    :param logical10: logical10, defaults to None
    :type logical10: bool, optional
    :param logical11: logical11, defaults to None
    :type logical11: bool, optional
    :param logical12: logical12, defaults to None
    :type logical12: bool, optional
    :param logical13: logical13, defaults to None
    :type logical13: bool, optional
    :param logical14: logical14, defaults to None
    :type logical14: bool, optional
    :param logical15: logical15, defaults to None
    :type logical15: bool, optional
    :param logical16: logical16, defaults to None
    :type logical16: bool, optional
    :param logical17: logical17, defaults to None
    :type logical17: bool, optional
    :param logical18: logical18, defaults to None
    :type logical18: bool, optional
    :param logical19: logical19, defaults to None
    :type logical19: bool, optional
    :param logical20: logical20, defaults to None
    :type logical20: bool, optional
    :param logical21: logical21, defaults to None
    :type logical21: bool, optional
    :param logical22: logical22, defaults to None
    :type logical22: bool, optional
    :param logical23: logical23, defaults to None
    :type logical23: bool, optional
    :param logical24: logical24, defaults to None
    :type logical24: bool, optional
    """

    def __init__(
        self,
        logical1: bool = None,
        logical2: bool = None,
        logical3: bool = None,
        logical4: bool = None,
        logical5: bool = None,
        logical6: bool = None,
        logical7: bool = None,
        logical8: bool = None,
        logical9: bool = None,
        logical10: bool = None,
        logical11: bool = None,
        logical12: bool = None,
        logical13: bool = None,
        logical14: bool = None,
        logical15: bool = None,
        logical16: bool = None,
        logical17: bool = None,
        logical18: bool = None,
        logical19: bool = None,
        logical20: bool = None,
        logical21: bool = None,
        logical22: bool = None,
        logical23: bool = None,
        logical24: bool = None,
        **kwargs
    ):
        """LogicalFields

        :param logical1: logical1, defaults to None
        :type logical1: bool, optional
        :param logical2: logical2, defaults to None
        :type logical2: bool, optional
        :param logical3: logical3, defaults to None
        :type logical3: bool, optional
        :param logical4: logical4, defaults to None
        :type logical4: bool, optional
        :param logical5: logical5, defaults to None
        :type logical5: bool, optional
        :param logical6: logical6, defaults to None
        :type logical6: bool, optional
        :param logical7: logical7, defaults to None
        :type logical7: bool, optional
        :param logical8: logical8, defaults to None
        :type logical8: bool, optional
        :param logical9: logical9, defaults to None
        :type logical9: bool, optional
        :param logical10: logical10, defaults to None
        :type logical10: bool, optional
        :param logical11: logical11, defaults to None
        :type logical11: bool, optional
        :param logical12: logical12, defaults to None
        :type logical12: bool, optional
        :param logical13: logical13, defaults to None
        :type logical13: bool, optional
        :param logical14: logical14, defaults to None
        :type logical14: bool, optional
        :param logical15: logical15, defaults to None
        :type logical15: bool, optional
        :param logical16: logical16, defaults to None
        :type logical16: bool, optional
        :param logical17: logical17, defaults to None
        :type logical17: bool, optional
        :param logical18: logical18, defaults to None
        :type logical18: bool, optional
        :param logical19: logical19, defaults to None
        :type logical19: bool, optional
        :param logical20: logical20, defaults to None
        :type logical20: bool, optional
        :param logical21: logical21, defaults to None
        :type logical21: bool, optional
        :param logical22: logical22, defaults to None
        :type logical22: bool, optional
        :param logical23: logical23, defaults to None
        :type logical23: bool, optional
        :param logical24: logical24, defaults to None
        :type logical24: bool, optional
        """
        if logical1 is not None:
            self.logical1 = logical1
        if logical2 is not None:
            self.logical2 = logical2
        if logical3 is not None:
            self.logical3 = logical3
        if logical4 is not None:
            self.logical4 = logical4
        if logical5 is not None:
            self.logical5 = logical5
        if logical6 is not None:
            self.logical6 = logical6
        if logical7 is not None:
            self.logical7 = logical7
        if logical8 is not None:
            self.logical8 = logical8
        if logical9 is not None:
            self.logical9 = logical9
        if logical10 is not None:
            self.logical10 = logical10
        if logical11 is not None:
            self.logical11 = logical11
        if logical12 is not None:
            self.logical12 = logical12
        if logical13 is not None:
            self.logical13 = logical13
        if logical14 is not None:
            self.logical14 = logical14
        if logical15 is not None:
            self.logical15 = logical15
        if logical16 is not None:
            self.logical16 = logical16
        if logical17 is not None:
            self.logical17 = logical17
        if logical18 is not None:
            self.logical18 = logical18
        if logical19 is not None:
            self.logical19 = logical19
        if logical20 is not None:
            self.logical20 = logical20
        if logical21 is not None:
            self.logical21 = logical21
        if logical22 is not None:
            self.logical22 = logical22
        if logical23 is not None:
            self.logical23 = logical23
        if logical24 is not None:
            self.logical24 = logical24
        self._kwargs = kwargs
