# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .object_group import ObjectGroup


@JsonMap({"total_count": "totalCount", "page_number": "pageNumber"})
class ObjectGroupPageResponse(BaseModel):
    """ObjectGroupPageResponse

    :param total_count: total_count, defaults to None
    :type total_count: int, optional
    :param page_number: page_number, defaults to None
    :type page_number: int, optional
    :param items: items, defaults to None
    :type items: List[ObjectGroup], optional
    """

    def __init__(
        self,
        total_count: int = None,
        page_number: int = None,
        items: List[ObjectGroup] = None,
        **kwargs,
    ):
        """ObjectGroupPageResponse

        :param total_count: total_count, defaults to None
        :type total_count: int, optional
        :param page_number: page_number, defaults to None
        :type page_number: int, optional
        :param items: items, defaults to None
        :type items: List[ObjectGroup], optional
        """
        if total_count is not None:
            self.total_count = total_count
        if page_number is not None:
            self.page_number = page_number
        if items is not None:
            self.items = self._define_list(items, ObjectGroup)
        self._kwargs = kwargs
